// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoleHub.Data;

#nullable disable

namespace SoleHub.Migrations
{
    [DbContext(typeof(SoleHubDbContext))]
    [Migration("20260508062043_AddWishlistItems")]
    partial class AddWishlistItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoleHub.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("SoleHub.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barangay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Courier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ShippingFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SoleHub.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SoleHub.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 13,
                            Brand = "Nike",
                            Category = "Running",
                            ImageUrl = "/images/nike16.png",
                            Name = "Nike Shoe 13",
                            Price = 4995.00m
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Nike",
                            Category = "Running",
                            ImageUrl = "/images/nike17.png",
                            Name = "Nike Shoe 14",
                            Price = 5495.00m
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Nike",
                            Category = "Running",
                            ImageUrl = "/images/nike18.png",
                            Name = "Nike Shoe 15",
                            Price = 5995.00m
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Nike",
                            Category = "Running",
                            ImageUrl = "/images/nike20.png",
                            Name = "Nike Shoe 16",
                            Price = 6495.00m
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Nike",
                            Category = "Running",
                            ImageUrl = "/images/nike21.png",
                            Name = "Nike Shoe 17",
                            Price = 6995.00m
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Nike",
                            Category = "Running",
                            ImageUrl = "/images/nikke19.png",
                            Name = "Nike Shoe 18",
                            Price = 7495.00m
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad1.png",
                            Name = "Adidas Shoe 19",
                            Price = 7995.00m
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad2.png",
                            Name = "Adidas Shoe 20",
                            Price = 8495.00m
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad3.png",
                            Name = "Adidas Shoe 21",
                            Price = 8995.00m
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad4.png",
                            Name = "Adidas Shoe 22",
                            Price = 9495.00m
                        },
                        new
                        {
                            Id = 23,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad6.png",
                            Name = "Adidas Shoe 23",
                            Price = 4995.00m
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad7.png",
                            Name = "Adidas Shoe 24",
                            Price = 5495.00m
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad8.png",
                            Name = "Adidas Shoe 25",
                            Price = 5995.00m
                        },
                        new
                        {
                            Id = 26,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad9.png",
                            Name = "Adidas Shoe 26",
                            Price = 6495.00m
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad10.png",
                            Name = "Adidas Shoe 27",
                            Price = 6995.00m
                        },
                        new
                        {
                            Id = 28,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad11.png",
                            Name = "Adidas Shoe 28",
                            Price = 7495.00m
                        },
                        new
                        {
                            Id = 29,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad12.png",
                            Name = "Adidas Shoe 29",
                            Price = 7995.00m
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad14.png",
                            Name = "Adidas Shoe 30",
                            Price = 8495.00m
                        },
                        new
                        {
                            Id = 31,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad15.png",
                            Name = "Adidas Shoe 31",
                            Price = 8995.00m
                        },
                        new
                        {
                            Id = 32,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad16.png",
                            Name = "Adidas Shoe 32",
                            Price = 9495.00m
                        },
                        new
                        {
                            Id = 33,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad17.png",
                            Name = "Adidas Shoe 33",
                            Price = 4995.00m
                        },
                        new
                        {
                            Id = 34,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad18.png",
                            Name = "Adidas Shoe 34",
                            Price = 5495.00m
                        },
                        new
                        {
                            Id = 35,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad19.png",
                            Name = "Adidas Shoe 35",
                            Price = 5995.00m
                        },
                        new
                        {
                            Id = 36,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad20.png",
                            Name = "Adidas Shoe 36",
                            Price = 6495.00m
                        },
                        new
                        {
                            Id = 37,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad22.png",
                            Name = "Adidas Shoe 37",
                            Price = 6995.00m
                        },
                        new
                        {
                            Id = 38,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad23.png",
                            Name = "Adidas Shoe 38",
                            Price = 7495.00m
                        },
                        new
                        {
                            Id = 39,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad24.png",
                            Name = "Adidas Shoe 39",
                            Price = 7995.00m
                        },
                        new
                        {
                            Id = 40,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad25.png",
                            Name = "Adidas Shoe 40",
                            Price = 8495.00m
                        },
                        new
                        {
                            Id = 41,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad26.png",
                            Name = "Adidas Shoe 41",
                            Price = 8995.00m
                        },
                        new
                        {
                            Id = 42,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad27.png",
                            Name = "Adidas Shoe 42",
                            Price = 9495.00m
                        },
                        new
                        {
                            Id = 43,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad28.png",
                            Name = "Adidas Shoe 43",
                            Price = 4995.00m
                        },
                        new
                        {
                            Id = 44,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad29.png",
                            Name = "Adidas Shoe 44",
                            Price = 5495.00m
                        },
                        new
                        {
                            Id = 45,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad30.png",
                            Name = "Adidas Shoe 45",
                            Price = 5995.00m
                        },
                        new
                        {
                            Id = 46,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad31.png",
                            Name = "Adidas Shoe 46",
                            Price = 6495.00m
                        },
                        new
                        {
                            Id = 47,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad32.png",
                            Name = "Adidas Shoe 47",
                            Price = 6995.00m
                        },
                        new
                        {
                            Id = 48,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad33.png",
                            Name = "Adidas Shoe 48",
                            Price = 7495.00m
                        },
                        new
                        {
                            Id = 49,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad34.png",
                            Name = "Adidas Shoe 49",
                            Price = 7995.00m
                        },
                        new
                        {
                            Id = 50,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad35.png",
                            Name = "Adidas Shoe 50",
                            Price = 8495.00m
                        },
                        new
                        {
                            Id = 51,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/ad36.png",
                            Name = "Adidas Shoe 51",
                            Price = 8995.00m
                        },
                        new
                        {
                            Id = 52,
                            Brand = "Nike",
                            Category = "Running",
                            ImageUrl = "/images/nike2.png",
                            Name = "Nike Shoe 52",
                            Price = 9495.00m
                        },
                        new
                        {
                            Id = 53,
                            Brand = "Nike",
                            Category = "Running",
                            ImageUrl = "/images/nike3.png",
                            Name = "Nike Shoe 53",
                            Price = 4995.00m
                        },
                        new
                        {
                            Id = 54,
                            Brand = "Nike",
                            Category = "Running",
                            ImageUrl = "/images/nike4.png",
                            Name = "Nike Shoe 54",
                            Price = 5495.00m
                        },
                        new
                        {
                            Id = 55,
                            Brand = "Nike",
                            Category = "Running",
                            ImageUrl = "/images/nike5.png",
                            Name = "Nike Shoe 55",
                            Price = 5995.00m
                        },
                        new
                        {
                            Id = 56,
                            Brand = "Nike",
                            Category = "Running",
                            ImageUrl = "/images/nike6.png",
                            Name = "Nike Shoe 56",
                            Price = 6495.00m
                        },
                        new
                        {
                            Id = 57,
                            Brand = "Nike",
                            Category = "Running",
                            ImageUrl = "/images/nike7.png",
                            Name = "Nike Shoe 57",
                            Price = 6995.00m
                        },
                        new
                        {
                            Id = 58,
                            Brand = "Nike",
                            Category = "Running",
                            ImageUrl = "/images/nike8.png",
                            Name = "Nike Shoe 58",
                            Price = 7495.00m
                        },
                        new
                        {
                            Id = 59,
                            Brand = "Nike",
                            Category = "Running",
                            ImageUrl = "/images/nike9.png",
                            Name = "Nike Shoe 59",
                            Price = 7995.00m
                        },
                        new
                        {
                            Id = 60,
                            Brand = "Nike",
                            Category = "Running",
                            ImageUrl = "/images/nike10.png",
                            Name = "Nike Shoe 60",
                            Price = 8495.00m
                        },
                        new
                        {
                            Id = 61,
                            Brand = "Nike",
                            Category = "Running",
                            ImageUrl = "/images/nike11.png",
                            Name = "Nike Shoe 61",
                            Price = 8995.00m
                        },
                        new
                        {
                            Id = 62,
                            Brand = "Nike",
                            Category = "Running",
                            ImageUrl = "/images/nike12.png",
                            Name = "Nike Shoe 62",
                            Price = 9495.00m
                        },
                        new
                        {
                            Id = 63,
                            Brand = "Nike",
                            Category = "Running",
                            ImageUrl = "/images/nike13.png",
                            Name = "Nike Shoe 63",
                            Price = 4995.00m
                        },
                        new
                        {
                            Id = 64,
                            Brand = "Nike",
                            Category = "Running",
                            ImageUrl = "/images/nike14.png",
                            Name = "Nike Shoe 64",
                            Price = 5495.00m
                        },
                        new
                        {
                            Id = 65,
                            Brand = "Nike",
                            Category = "Running",
                            ImageUrl = "/images/nike15.png",
                            Name = "Nike Shoe 65",
                            Price = 5995.00m
                        },
                        new
                        {
                            Id = 66,
                            Brand = "New Balance",
                            Category = "Running",
                            ImageUrl = "/images/nb1.png",
                            Name = "New Balance Shoe 66",
                            Price = 6495.00m
                        },
                        new
                        {
                            Id = 67,
                            Brand = "New Balance",
                            Category = "Running",
                            ImageUrl = "/images/nb2.png",
                            Name = "New Balance Shoe 67",
                            Price = 6995.00m
                        },
                        new
                        {
                            Id = 68,
                            Brand = "New Balance",
                            Category = "Running",
                            ImageUrl = "/images/nb3.png",
                            Name = "New Balance Shoe 68",
                            Price = 7495.00m
                        },
                        new
                        {
                            Id = 69,
                            Brand = "New Balance",
                            Category = "Running",
                            ImageUrl = "/images/nb4.png",
                            Name = "New Balance Shoe 69",
                            Price = 7995.00m
                        },
                        new
                        {
                            Id = 70,
                            Brand = "New Balance",
                            Category = "Running",
                            ImageUrl = "/images/nb5.png",
                            Name = "New Balance Shoe 70",
                            Price = 8495.00m
                        },
                        new
                        {
                            Id = 71,
                            Brand = "New Balance",
                            Category = "Running",
                            ImageUrl = "/images/nb6.png",
                            Name = "New Balance Shoe 71",
                            Price = 8995.00m
                        },
                        new
                        {
                            Id = 72,
                            Brand = "New Balance",
                            Category = "Running",
                            ImageUrl = "/images/nb7.png",
                            Name = "New Balance Shoe 72",
                            Price = 9495.00m
                        },
                        new
                        {
                            Id = 73,
                            Brand = "New Balance",
                            Category = "Running",
                            ImageUrl = "/images/nb202rbl.png",
                            Name = "New Balance Shoe 73",
                            Price = 4995.00m
                        },
                        new
                        {
                            Id = 74,
                            Brand = "Hoka",
                            Category = "Running",
                            ImageUrl = "/images/hoka1.png",
                            Name = "Hoka Shoe 74",
                            Price = 5495.00m
                        },
                        new
                        {
                            Id = 75,
                            Brand = "Hoka",
                            Category = "Running",
                            ImageUrl = "/images/hoka2.png",
                            Name = "Hoka Shoe 75",
                            Price = 5995.00m
                        },
                        new
                        {
                            Id = 76,
                            Brand = "Hoka",
                            Category = "Running",
                            ImageUrl = "/images/hoka5.png",
                            Name = "Hoka Shoe 76",
                            Price = 6495.00m
                        },
                        new
                        {
                            Id = 77,
                            Brand = "Vans",
                            Category = "Skate",
                            ImageUrl = "/images/vans1.png",
                            Name = "Vans Shoe 77",
                            Price = 6995.00m
                        },
                        new
                        {
                            Id = 78,
                            Brand = "Vans",
                            Category = "Skate",
                            ImageUrl = "/images/vans2.png",
                            Name = "Vans Shoe 78",
                            Price = 7495.00m
                        },
                        new
                        {
                            Id = 79,
                            Brand = "Vans",
                            Category = "Skate",
                            ImageUrl = "/images/vans3.png",
                            Name = "Vans Shoe 79",
                            Price = 7995.00m
                        },
                        new
                        {
                            Id = 80,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c2.png",
                            Name = "SoleHub Shoe 80",
                            Price = 8495.00m
                        },
                        new
                        {
                            Id = 81,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c3.png",
                            Name = "SoleHub Shoe 81",
                            Price = 8995.00m
                        },
                        new
                        {
                            Id = 82,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c4.png",
                            Name = "SoleHub Shoe 82",
                            Price = 9495.00m
                        },
                        new
                        {
                            Id = 83,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c5.png",
                            Name = "SoleHub Shoe 83",
                            Price = 4995.00m
                        },
                        new
                        {
                            Id = 84,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c6.png",
                            Name = "SoleHub Shoe 84",
                            Price = 5495.00m
                        },
                        new
                        {
                            Id = 85,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c7.png",
                            Name = "SoleHub Shoe 85",
                            Price = 5995.00m
                        },
                        new
                        {
                            Id = 86,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c8.png",
                            Name = "SoleHub Shoe 86",
                            Price = 6495.00m
                        },
                        new
                        {
                            Id = 87,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c9.png",
                            Name = "SoleHub Shoe 87",
                            Price = 6995.00m
                        },
                        new
                        {
                            Id = 88,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c10.png",
                            Name = "SoleHub Shoe 88",
                            Price = 7495.00m
                        },
                        new
                        {
                            Id = 89,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c11.png",
                            Name = "SoleHub Shoe 89",
                            Price = 7995.00m
                        },
                        new
                        {
                            Id = 90,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c12.png",
                            Name = "SoleHub Shoe 90",
                            Price = 8495.00m
                        },
                        new
                        {
                            Id = 91,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c13.png",
                            Name = "SoleHub Shoe 91",
                            Price = 8995.00m
                        },
                        new
                        {
                            Id = 92,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c14.png",
                            Name = "SoleHub Shoe 92",
                            Price = 9495.00m
                        },
                        new
                        {
                            Id = 93,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c15.png",
                            Name = "SoleHub Shoe 93",
                            Price = 4995.00m
                        },
                        new
                        {
                            Id = 94,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c16.png",
                            Name = "SoleHub Shoe 94",
                            Price = 5495.00m
                        },
                        new
                        {
                            Id = 95,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c17.png",
                            Name = "SoleHub Shoe 95",
                            Price = 5995.00m
                        },
                        new
                        {
                            Id = 96,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c18.png",
                            Name = "SoleHub Shoe 96",
                            Price = 6495.00m
                        },
                        new
                        {
                            Id = 97,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c19.png",
                            Name = "SoleHub Shoe 97",
                            Price = 6995.00m
                        },
                        new
                        {
                            Id = 98,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c20.png",
                            Name = "SoleHub Shoe 98",
                            Price = 7495.00m
                        },
                        new
                        {
                            Id = 99,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c21.png",
                            Name = "SoleHub Shoe 99",
                            Price = 7995.00m
                        },
                        new
                        {
                            Id = 100,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c23.png",
                            Name = "SoleHub Shoe 100",
                            Price = 8495.00m
                        },
                        new
                        {
                            Id = 101,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c24.png",
                            Name = "SoleHub Shoe 101",
                            Price = 8995.00m
                        },
                        new
                        {
                            Id = 102,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c25.png",
                            Name = "SoleHub Shoe 102",
                            Price = 9495.00m
                        },
                        new
                        {
                            Id = 103,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c26.png",
                            Name = "SoleHub Shoe 103",
                            Price = 4995.00m
                        },
                        new
                        {
                            Id = 104,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c27.png",
                            Name = "SoleHub Shoe 104",
                            Price = 5495.00m
                        },
                        new
                        {
                            Id = 105,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c28.png",
                            Name = "SoleHub Shoe 105",
                            Price = 5995.00m
                        },
                        new
                        {
                            Id = 106,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c29.png",
                            Name = "SoleHub Shoe 106",
                            Price = 6495.00m
                        },
                        new
                        {
                            Id = 107,
                            Brand = "SoleHub",
                            Category = "Lifestyle",
                            ImageUrl = "/images/c30.png",
                            Name = "SoleHub Shoe 107",
                            Price = 6995.00m
                        },
                        new
                        {
                            Id = 108,
                            Brand = "Puma",
                            Category = "Lifestyle",
                            ImageUrl = "/images/p1.png",
                            Name = "Puma Shoe 108",
                            Price = 7495.00m
                        },
                        new
                        {
                            Id = 109,
                            Brand = "Puma",
                            Category = "Lifestyle",
                            ImageUrl = "/images/p2.png",
                            Name = "Puma Shoe 109",
                            Price = 7995.00m
                        },
                        new
                        {
                            Id = 110,
                            Brand = "Puma",
                            Category = "Lifestyle",
                            ImageUrl = "/images/p3.png",
                            Name = "Puma Shoe 110",
                            Price = 8495.00m
                        },
                        new
                        {
                            Id = 111,
                            Brand = "Puma",
                            Category = "Lifestyle",
                            ImageUrl = "/images/p4.png",
                            Name = "Puma Shoe 111",
                            Price = 8995.00m
                        },
                        new
                        {
                            Id = 112,
                            Brand = "Puma",
                            Category = "Lifestyle",
                            ImageUrl = "/images/p5.png",
                            Name = "Puma Shoe 112",
                            Price = 9495.00m
                        },
                        new
                        {
                            Id = 113,
                            Brand = "Puma",
                            Category = "Lifestyle",
                            ImageUrl = "/images/p6.png",
                            Name = "Puma Shoe 113",
                            Price = 4995.00m
                        },
                        new
                        {
                            Id = 114,
                            Brand = "Puma",
                            Category = "Lifestyle",
                            ImageUrl = "/images/p7.png",
                            Name = "Puma Shoe 114",
                            Price = 5495.00m
                        },
                        new
                        {
                            Id = 115,
                            Brand = "Puma",
                            Category = "Lifestyle",
                            ImageUrl = "/images/p8.png",
                            Name = "Puma Shoe 115",
                            Price = 5995.00m
                        },
                        new
                        {
                            Id = 116,
                            Brand = "Puma",
                            Category = "Lifestyle",
                            ImageUrl = "/images/p9.png",
                            Name = "Puma Shoe 116",
                            Price = 6495.00m
                        },
                        new
                        {
                            Id = 117,
                            Brand = "Puma",
                            Category = "Lifestyle",
                            ImageUrl = "/images/p10.png",
                            Name = "Puma Shoe 117",
                            Price = 6995.00m
                        },
                        new
                        {
                            Id = 118,
                            Brand = "Puma",
                            Category = "Lifestyle",
                            ImageUrl = "/images/p11.png",
                            Name = "Puma Shoe 118",
                            Price = 7495.00m
                        },
                        new
                        {
                            Id = 119,
                            Brand = "Puma",
                            Category = "Lifestyle",
                            ImageUrl = "/images/p12.png",
                            Name = "Puma Shoe 119",
                            Price = 7995.00m
                        },
                        new
                        {
                            Id = 120,
                            Brand = "Puma",
                            Category = "Lifestyle",
                            ImageUrl = "/images/p13.png",
                            Name = "Puma Shoe 120",
                            Price = 8495.00m
                        },
                        new
                        {
                            Id = 121,
                            Brand = "Puma",
                            Category = "Lifestyle",
                            ImageUrl = "/images/p14.png",
                            Name = "Puma Shoe 121",
                            Price = 8995.00m
                        },
                        new
                        {
                            Id = 122,
                            Brand = "Puma",
                            Category = "Lifestyle",
                            ImageUrl = "/images/p15.png",
                            Name = "Puma Shoe 122",
                            Price = 9495.00m
                        },
                        new
                        {
                            Id = 123,
                            Brand = "Puma",
                            Category = "Lifestyle",
                            ImageUrl = "/images/p16.png",
                            Name = "Puma Shoe 123",
                            Price = 4995.00m
                        },
                        new
                        {
                            Id = 124,
                            Brand = "Puma",
                            Category = "Lifestyle",
                            ImageUrl = "/images/p17.png",
                            Name = "Puma Shoe 124",
                            Price = 5495.00m
                        },
                        new
                        {
                            Id = 125,
                            Brand = "Puma",
                            Category = "Lifestyle",
                            ImageUrl = "/images/p18.png",
                            Name = "Puma Shoe 125",
                            Price = 5995.00m
                        },
                        new
                        {
                            Id = 126,
                            Brand = "Puma",
                            Category = "Lifestyle",
                            ImageUrl = "/images/p19.png",
                            Name = "Puma Shoe 126",
                            Price = 6495.00m
                        },
                        new
                        {
                            Id = 127,
                            Brand = "Puma",
                            Category = "Lifestyle",
                            ImageUrl = "/images/p20.png",
                            Name = "Puma Shoe 127",
                            Price = 6995.00m
                        },
                        new
                        {
                            Id = 128,
                            Brand = "Puma",
                            Category = "Lifestyle",
                            ImageUrl = "/images/p21.png",
                            Name = "Puma Shoe 128",
                            Price = 7495.00m
                        },
                        new
                        {
                            Id = 129,
                            Brand = "Puma",
                            Category = "Lifestyle",
                            ImageUrl = "/images/p22.png",
                            Name = "Puma Shoe 129",
                            Price = 7995.00m
                        },
                        new
                        {
                            Id = 130,
                            Brand = "Puma",
                            Category = "Lifestyle",
                            ImageUrl = "/images/p23.png",
                            Name = "Puma Shoe 130",
                            Price = 8495.00m
                        },
                        new
                        {
                            Id = 131,
                            Brand = "Puma",
                            Category = "Lifestyle",
                            ImageUrl = "/images/p24.png",
                            Name = "Puma Shoe 131",
                            Price = 8995.00m
                        },
                        new
                        {
                            Id = 132,
                            Brand = "Puma",
                            Category = "Lifestyle",
                            ImageUrl = "/images/p25.png",
                            Name = "Puma Shoe 132",
                            Price = 9495.00m
                        },
                        new
                        {
                            Id = 133,
                            Brand = "Reebok",
                            Category = "Running",
                            ImageUrl = "/images/r1.png",
                            Name = "Reebok Shoe 133",
                            Price = 4995.00m
                        },
                        new
                        {
                            Id = 134,
                            Brand = "Reebok",
                            Category = "Running",
                            ImageUrl = "/images/r2.png",
                            Name = "Reebok Shoe 134",
                            Price = 5495.00m
                        },
                        new
                        {
                            Id = 135,
                            Brand = "Reebok",
                            Category = "Running",
                            ImageUrl = "/images/r4.png",
                            Name = "Reebok Shoe 135",
                            Price = 5995.00m
                        },
                        new
                        {
                            Id = 136,
                            Brand = "Reebok",
                            Category = "Running",
                            ImageUrl = "/images/r5.png",
                            Name = "Reebok Shoe 136",
                            Price = 6495.00m
                        },
                        new
                        {
                            Id = 137,
                            Brand = "Reebok",
                            Category = "Running",
                            ImageUrl = "/images/r6.png",
                            Name = "Reebok Shoe 137",
                            Price = 6995.00m
                        },
                        new
                        {
                            Id = 138,
                            Brand = "Reebok",
                            Category = "Running",
                            ImageUrl = "/images/r7.png",
                            Name = "Reebok Shoe 138",
                            Price = 7495.00m
                        },
                        new
                        {
                            Id = 139,
                            Brand = "Reebok",
                            Category = "Running",
                            ImageUrl = "/images/r8.png",
                            Name = "Reebok Shoe 139",
                            Price = 7995.00m
                        },
                        new
                        {
                            Id = 140,
                            Brand = "Reebok",
                            Category = "Running",
                            ImageUrl = "/images/r9.png",
                            Name = "Reebok Shoe 140",
                            Price = 8495.00m
                        },
                        new
                        {
                            Id = 141,
                            Brand = "Reebok",
                            Category = "Running",
                            ImageUrl = "/images/r10.png",
                            Name = "Reebok Shoe 141",
                            Price = 8995.00m
                        },
                        new
                        {
                            Id = 142,
                            Brand = "Reebok",
                            Category = "Running",
                            ImageUrl = "/images/r11.png",
                            Name = "Reebok Shoe 142",
                            Price = 9495.00m
                        },
                        new
                        {
                            Id = 143,
                            Brand = "Reebok",
                            Category = "Running",
                            ImageUrl = "/images/r12.png",
                            Name = "Reebok Shoe 143",
                            Price = 4995.00m
                        },
                        new
                        {
                            Id = 144,
                            Brand = "Reebok",
                            Category = "Running",
                            ImageUrl = "/images/r13.png",
                            Name = "Reebok Shoe 144",
                            Price = 5495.00m
                        },
                        new
                        {
                            Id = 145,
                            Brand = "Reebok",
                            Category = "Running",
                            ImageUrl = "/images/r14.png",
                            Name = "Reebok Shoe 145",
                            Price = 5995.00m
                        },
                        new
                        {
                            Id = 146,
                            Brand = "Reebok",
                            Category = "Running",
                            ImageUrl = "/images/r15.png",
                            Name = "Reebok Shoe 146",
                            Price = 6495.00m
                        },
                        new
                        {
                            Id = 147,
                            Brand = "Reebok",
                            Category = "Running",
                            ImageUrl = "/images/r16.png",
                            Name = "Reebok Shoe 147",
                            Price = 6995.00m
                        },
                        new
                        {
                            Id = 148,
                            Brand = "Reebok",
                            Category = "Running",
                            ImageUrl = "/images/r17.png",
                            Name = "Reebok Shoe 148",
                            Price = 7495.00m
                        },
                        new
                        {
                            Id = 149,
                            Brand = "Skechers",
                            Category = "Lifestyle",
                            ImageUrl = "/images/s1.png",
                            Name = "Skechers Shoe 149",
                            Price = 7995.00m
                        },
                        new
                        {
                            Id = 150,
                            Brand = "Skechers",
                            Category = "Lifestyle",
                            ImageUrl = "/images/s2.png",
                            Name = "Skechers Shoe 150",
                            Price = 8495.00m
                        },
                        new
                        {
                            Id = 151,
                            Brand = "Skechers",
                            Category = "Lifestyle",
                            ImageUrl = "/images/s3.png",
                            Name = "Skechers Shoe 151",
                            Price = 8995.00m
                        },
                        new
                        {
                            Id = 152,
                            Brand = "Skechers",
                            Category = "Lifestyle",
                            ImageUrl = "/images/s4.png",
                            Name = "Skechers Shoe 152",
                            Price = 9495.00m
                        },
                        new
                        {
                            Id = 153,
                            Brand = "Skechers",
                            Category = "Lifestyle",
                            ImageUrl = "/images/s5.png",
                            Name = "Skechers Shoe 153",
                            Price = 4995.00m
                        },
                        new
                        {
                            Id = 154,
                            Brand = "Skechers",
                            Category = "Lifestyle",
                            ImageUrl = "/images/s6.png",
                            Name = "Skechers Shoe 154",
                            Price = 5495.00m
                        },
                        new
                        {
                            Id = 155,
                            Brand = "Skechers",
                            Category = "Lifestyle",
                            ImageUrl = "/images/s7.png",
                            Name = "Skechers Shoe 155",
                            Price = 5995.00m
                        },
                        new
                        {
                            Id = 156,
                            Brand = "Skechers",
                            Category = "Lifestyle",
                            ImageUrl = "/images/s8.png",
                            Name = "Skechers Shoe 156",
                            Price = 6495.00m
                        },
                        new
                        {
                            Id = 157,
                            Brand = "Skechers",
                            Category = "Lifestyle",
                            ImageUrl = "/images/s9.png",
                            Name = "Skechers Shoe 157",
                            Price = 6995.00m
                        });
                });

            modelBuilder.Entity("SoleHub.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "SoleHub Admin",
                            Password = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Juan Dela Cruz",
                            Password = "customer123",
                            Role = "Customer",
                            Username = "customer"
                        });
                });

            modelBuilder.Entity("SoleHub.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cebu City, Philippines",
                            Email = "admin@solehub.com",
                            FullName = "SoleHub Admin",
                            ProfilePictureUrl = ""
                        },
                        new
                        {
                            Id = 2,
                            Address = "Cebu City, Philippines",
                            Email = "customer@solehub.com",
                            FullName = "Juan Dela Cruz",
                            ProfilePictureUrl = ""
                        });
                });

            modelBuilder.Entity("SoleHub.Models.WishlistItem", b =>
                {
                    b.Property<int>("WishlistItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WishlistItemId"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WishlistItemId");

                    b.HasIndex("ProductId");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("SoleHub.Models.CartItem", b =>
                {
                    b.HasOne("SoleHub.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoleHub.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SoleHub.Models.Order", b =>
                {
                    b.HasOne("SoleHub.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SoleHub.Models.OrderItem", b =>
                {
                    b.HasOne("SoleHub.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SoleHub.Models.WishlistItem", b =>
                {
                    b.HasOne("SoleHub.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SoleHub.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
