// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoleHub.Data;

#nullable disable

namespace SoleHub.Migrations
{
    [DbContext(typeof(SoleHubDbContext))]
    [Migration("20260427133533_AddLoginAndPhilippineShipping")]
    partial class AddLoginAndPhilippineShipping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoleHub.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("SoleHub.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barangay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Courier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ShippingFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SoleHub.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SoleHub.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Nike",
                            Category = "Running",
                            ImageUrl = "/images/alphafly.jpg",
                            Name = "Alphafly Next%",
                            Price = 15995.00m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Adidas",
                            Category = "Slides",
                            ImageUrl = "/images/yeezy.jpg",
                            Name = "Yeezy Slides",
                            Price = 3999.00m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Crocs",
                            Category = "Slides",
                            ImageUrl = "/images/crocs.jpg",
                            Name = "Classic All-Terrain",
                            Price = 3499.00m
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Nike",
                            Category = "Lifestyle",
                            ImageUrl = "/images/aj1.jpg",
                            Name = "Air Jordan 1 Low",
                            Price = 6995.00m
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Adidas",
                            Category = "Running",
                            ImageUrl = "/images/ultraboost.jpg",
                            Name = "Ultraboost Light",
                            Price = 9995.00m
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/forum.jpg",
                            Name = "Forum Low",
                            Price = 5995.00m
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Vans",
                            Category = "Skate",
                            ImageUrl = "/images/vans.jpg",
                            Name = "Old Skool",
                            Price = 4298.00m
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Converse",
                            Category = "Lifestyle",
                            ImageUrl = "/images/converse.jpg",
                            Name = "Chuck Taylor 70",
                            Price = 3890.00m
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Nike",
                            Category = "Lifestyle",
                            ImageUrl = "/images/dunk.jpg",
                            Name = "Dunk Low Retro",
                            Price = 6895.00m
                        },
                        new
                        {
                            Id = 10,
                            Brand = "On",
                            Category = "Running",
                            ImageUrl = "/images/on.jpg",
                            Name = "Cloudmonster",
                            Price = 10995.00m
                        },
                        new
                        {
                            Id = 11,
                            Brand = "ASICS",
                            Category = "Running",
                            ImageUrl = "/images/asics.jpg",
                            Name = "Gel-Kayano 30",
                            Price = 9995.00m
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Adidas",
                            Category = "Lifestyle",
                            ImageUrl = "/images/samba.jpg",
                            Name = "Samba OG",
                            Price = 5995.00m
                        });
                });

            modelBuilder.Entity("SoleHub.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "SoleHub Admin",
                            Password = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Juan Dela Cruz",
                            Password = "customer123",
                            Role = "Customer",
                            Username = "customer"
                        });
                });

            modelBuilder.Entity("SoleHub.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cebu City, Philippines",
                            Email = "admin@solehub.com",
                            FullName = "SoleHub Admin",
                            ProfilePictureUrl = ""
                        },
                        new
                        {
                            Id = 2,
                            Address = "Cebu City, Philippines",
                            Email = "customer@solehub.com",
                            FullName = "Juan Dela Cruz",
                            ProfilePictureUrl = ""
                        });
                });

            modelBuilder.Entity("SoleHub.Models.CartItem", b =>
                {
                    b.HasOne("SoleHub.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoleHub.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SoleHub.Models.Order", b =>
                {
                    b.HasOne("SoleHub.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SoleHub.Models.OrderItem", b =>
                {
                    b.HasOne("SoleHub.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SoleHub.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
